### ISSUE TITLE
When Chatting if the message is last the scrollbar is not following

### ISSUE THREAD

**Issue by deruelle** [RestComm/olympus#80] opened 2016-12-16 11:03 UTC
When chatting, after each message the scrollbar is not following the last message automatically, and users need to scroll down manually to reach the bottom of the chat screen.

**Comment by maria-farooq** [comment] 2016-12-30 18:03
I think its duplicate of #65

**Comment by ammendonca** [comment] 2017-04-12 13:56
Fixed by 14c9327.

**Closed by ammendonca** 2017-04-12 13:56 UTC
