### ISSUE TITLE
Problem Using chrome DTMF.

### ISSUE THREAD

**Issue by leftyb** [RestComm/olympus#81] opened 2016-12-19 16:26 UTC
Problem when calling OUTBOUND PSTN from Olympus using Chrome on OSX.
Logs:https://app.box.com/files/0/f/14728485081/Chrome_dtmf_issue

**Comment by deruelle** [comment] 2016-12-19 16:29
@leftyb can you provide a bit more description context and what was found from the initial investigation ?

**Comment by deruelle** [comment] 2016-12-20 14:04
@hrosa can you have a look here as well in the logs for insights ?

**Comment by leftyb** [comment] 2016-12-20 14:24
The issue seems to be that when a DTMF tone has pressed at the Olympus Keypad, more than one tones are actually generated, from one key press. 

So RMS is actually detecting erroneously due to that. E.g as can be seen at the pcap instead of one RTP EVENT for the KEY 6 is seems that more than 6 are send.

**Comment by atsakiridis** [comment] 2016-12-22 10:22
@leftyb do we have Chrome Olympus logs for that that I can check? Is this 100% reproducible at cloud? Can I try there? Is the scenario as simple as just calling a gather App and sending digits? 

@hrosa did you get a chance to have a look at the MS side? I recall having some issues with DTMF in the past. Also, do you remember of the top of your head if chrome employs inband our out of band RTP DTMF?

**Comment by leftyb** [comment] 2016-12-22 10:36
@atsakiridis We dont have at the moment but John can reproduce it. Yes the incident was reported at cloud. The scenario is not that simple, on calling  a simple DTMF app. 
You need to do an OUTBOUND PSTN call where there is an IVR at the other end with DTMF. Just calling INBOUND with a simple DTMF app should work properly as we don't have any report issue. As well the same scenario worked on FF.

**Comment by hrosa** [comment] 2016-12-23 12:49
RestComm Media Server format is .wav (Sample rate of 8000Hz, bit rate of 8, Mono)

Helpful command to convert audio files for RMS compliance:
ffmpeg -i source_file.wav -acodec pcm_s16le -ac 1 -ar 8000 result_file.wav

**Comment by leftyb** [comment] 2016-12-23 13:00
After testing more, the information changes. It seems a chrome only issue. FF is not working either but due to different reason (Because FF is using SIP info, and is not supported from the SIP gw).

**Comment by atsakiridis** [comment] 2016-12-23 13:29
Some further insights we have made so far:
- Olympus for Firefox, Android and iOS might work due to the DTMF tones being recorded from the loudspeaker and sent together with the voice stream (unless sound is muted somehow, in which case it will not work)
- Olympus for Chrome uses RTP OOB as provided by PeerConnection DTMFSender. Traffic coming from client suggests that client sends a single DTMF digit (i.e. there's only one RTP packet marked 'Mark'). So it's like MS is somehow receiving one digit, but forwarding 3 digits instead

**Comment by atsakiridis** [comment] 2017-01-02 11:47
Closing this as evidence so far indicate an MS issue, and there's already an open ZD issue on that: https://telestax.zendesk.com/agent/tickets/33771

**Closed by atsakiridis** 2017-01-02 11:47 UTC
Labels: bug
